###  List of packages to install. The following installation steps are just a guide and may go wrong!  Set your repository first.
library("devtools")
install.packages("tidyverse")
install.packages("rstan")
install.packages("phytools")
install.packages("digest")
install.packages("metafor")
install.packages("RColorBrewer")
install.packages("colorspace")
install.packages("pheatmap")
install.packages("yaml")
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("MutationalPatterns")
BiocManager::install("TxDb.Hsapiens.UCSC.hg19.knownGene")
BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")
devtools::install_github("NickWilliamsSanger/rsimpop")
devtools::install_github("NickWilliamsSanger/rtreefit",build_vignettes=TRUE)
devtools::install_git("https://github.com/NickWilliamsSanger/treemut")
